name: Java CI

on: [push]

jobs:
  build-ubuntu-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: '19.3.0.2.java11'
      - run: java -version
      - run: gu install native-image
      - name: Build with Maven
        run: mvn -B package --file pom.xml -P build-native
      - name: Rename the artifact to OS-unique name
        shell: bash
        run: |
          ls -l target
          value=`cp target/net.majakorpi.jwt.jwtassertiongenerator target/jwtgen-${{ matrix.os }}`
      - name: Publish artifact
        uses: actions/upload-artifact@master
        with:
          name: jwtgen-${{ matrix.os }}
          path: target/jwtgen-${{ matrix.os }}

  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: '19.3.0.2.java11'
      - run: java -version
      - run: echo $env:java_home
      - run: dir $env:java_home\bin
      - name: Set up Visual C Build Tools Workload for Visual Studio 2017 Build Tools
        run: |
          choco install visualstudio2017-workload-vctools
      - name: set env variables and run the Maven build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          echo %JAVA_HOME%
          java -version
          mvn -X -B package --file pom.xml
      - run: . $env:java_home\bin\native-image -jar target\jwt_assert-1.0-SNAPSHOT.jar
      - name: Rename the artifact to OS-unique name
        shell: bash
        run: |
          ls -l target
          value=`cp jwt_assert-1.0-SNAPSHOT target/jwtgen-${{ matrix.os }}`
      - name: Publish artifact
        uses: actions/upload-artifact@master
        with:
          name: jwtgen-${{ matrix.os }}
          path: target/jwtgen-${{ matrix.os }}
